### ISSUE TITLE
Failing publish

### ISSUE THREAD

**Issue by sanders41** [thedataquarry/old-zola-site#1]
I saw your publish is failing. I'm not sure if there is a specific reason that you have split build and deploy? If not, my site also uses Zola and publishes without issue.  Here is my build/deploy action https://github.com/sanders41/sanders41.github.io/blob/main/.github/workflows/cd.yml if it helps.

**Comment by prrao87** [comment]
Hi @sanders41 thanks a lot for chiming in! I did use a similar action as you did and it worked to completion, but it doesn't do the `deploy`. As you can see, it shows that the publish is successful with the same action as you have, but the "deployments" section on the right sidebar doesn't ever update. No idea why.

I'm wondering if this is because the account that's performing the action is my personal one, but the GitHub Pages site is for an organization. Do you think it's something to do with the `GITHUB_TOKEN` being different for my personal account and the one that's associated with the organization in which this repo sits? Can't seem to figure it out.

**Note**: My goal is to to migrate my static blog site from Hugo to Zola, but I want to avoid any downtime on my blog -- that's why I thought of setting up a Zola blog with the static files in a separate organization's repo while I still have the old site (running on Hugo) up and running which is hosted on my personal account's GitHub Pages. Hope that makes sense!

**Comment by prrao87** [comment]
I've checked the logs and it seems to have completed the deployment without issue. Yet, it doesn't show that on the right sidebar, and the site isn't actually up and running on `https://thedataquarry.github.io`

```
Run shalzz/zola-deploy-action@v0.17.2
/usr/bin/docker run --name a7[5](https://github.com/thedataquarry/thedataquarry.github.io/actions/runs/7012840229/job/19078048383#step:4:6)34c23[6](https://github.com/thedataquarry/thedataquarry.github.io/actions/runs/7012840229/job/19078048383#step:4:7)729d249a44cac9e2d709fd9488f0d_ed3f8e --label a7534c --workdir /github/workspace --rm -e "PAGES_BRANCH" -e "TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/thedataquarry.github.io/thedataquarry.github.io":"/github/workspace" a7534c:236729d249a44cac9e2d709fd9488f0d
Starting deploy...
Building in . directory
Set safe directories
Fetching themes
Using zola 0.1[7](https://github.com/thedataquarry/thedataquarry.github.io/actions/runs/7012840229/job/19078048383#step:4:8).2
Building with flags:
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 2 pages (0 orphan) and 3 sections
Done in 51ms.

Pushing artifacts to thedataquarry/thedataquarry.github.io:gh-pages
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /github/workspace/public/.git/
[master (root-commit) ad5fbaf] Deploy thedataquarry/thedataquarry.github.io to thedataquarry/thedataquarry.github.io:gh-pages
 49 files changed, 624 insertions(+)
 create mode 100644 404.html
 create mode 100644 about/index.html
 create mode 100644 atom.xml
 create mode 100644 categories/general/index.html
 create mode 100644 categories/index.html
 create mode 100644 font/IBMPlexSans-Regular.woff2
 create mode 100644 giscus_dark.css
 create mode 100644 giscus_light.css
 create mode 100644 hl-dark.css
 create mode 100644 hl-light.css
 create mode 100644 icon/alert.svg
 create mode 100644 icon/arrow-up.svg
 create mode 100644 icon/backlink.svg
 create mode 100644 icon/buymeacoffee.svg
 create mode 100644 icon/check.svg
 create mode 100644 icon/copy.svg
 create mode 100644 icon/email.svg
 create mode 100644 icon/fingerprint.svg
 create mode 100644 icon/github.svg
 create mode 100644 icon/important.svg
 create mode 100644 icon/linkedin.svg
 create mode 100644 icon/moon.svg
 create mode 100644 icon/note.svg
 create mode 100644 icon/question.svg
 create mode 100644 icon/rss.svg
 create mode 100644 icon/stackoverflow.svg
 create mode 100644 icon/sun.svg
 create mode 100644 icon/tip.svg
 create mode 100644 icon/toc.svg
 create mode 100644 icon/twitter.svg
 create mode 100644 icon/warning.svg
 create mode 100644 img/dataquarry-banner.png
 create mode 100644 img/prao.png
 create mode 100644 index.html
 create mode 100644 js/lightense.min.js
 create mode 100644 js/main.js
 create mode 100644 main.css
 create mode 100644 posts/atom.xml
 create mode 100644 posts/hello-world/index.html
 create mode 100644 posts/index.html
 create mode 100644 posts/sample-post/index.html
 create mode 100644 projects/data.toml
 create mode 100644 projects/index.html
 create mode 100644 robots.txt
 create mode 100644 sitemap.xml
 create mode 100644 tags/general/index.html
 create mode 100644 tags/index.html
 create mode 100644 tags/markdown/index.html
 create mode 100644 tags/rust/index.html
To https://github.com/thedataquarry/thedataquarry.github.io.git
 + [8](https://github.com/thedataquarry/thedataquarry.github.io/actions/runs/7012840229/job/19078048383#step:4:9)81ec[9](https://github.com/thedataquarry/thedataquarry.github.io/actions/runs/7012840229/job/19078048383#step:4:10)d...ad5fbaf master -> gh-pages (forced update)
Deploy complete
```

**Comment by sanders41** [comment]
I have done GitHub pages for an org and never had issues with the token so I don't _think_ that is the problem. It's weird that it goes through completion, but doesn't actually deploy.

In `Settings` -> `Pages` is it set to deploy from a branch, and to use `gh-pages` as the branch?

**Comment by prrao87** [comment]
OMG I had it set to deploy via the action and not to deploy from the `gh-pages` branch! No wonder it wasn't doing anything! (Which is weird as my current Hugo blog is also set up the same way and it deploys fine there. Thanks so much for your tips, this was bugging me all day 😅

I absolutely love Zola, should be an absolute joy using it!

**Comment by sanders41** [comment]
Glad you got it working. I have enjoyed Zola, I think you will like it.

**Comment by prrao87** [comment]
Hey @sanders41 I used the exact same action that you did, and it was building a couple days ago (which is the same time you built your site last, I believe). However, it continually fails the build now. Could you try rebuilding the site now and let me know how you go? 

I reverted to the previous version of the deploy action, `0.17.1` and weirdly, that worked.

**Comment by sanders41** [comment]
I reran my last build and it didn't have any errors. I compared our deploy scripts and don't see a difference. I'm using 0.17.2 so I don't know why mine would deploy and yours doesn't. On a quick look I don't see any reason. I'll take a closer look in a bit and see if I can figure something out...it has me curious.

**Comment by prrao87** [comment]
Thanks! The lack of determinism is what's driving me crazy. If the same action on a different day behaves differently, it makes me wonder about using it long term. It makes no sense why the older version works (deterministically), but the new one is random and stopped working for no reason.

I've never had a build deployment failure with my Hugo actions before. Glad you've had some level of experience with Zola deployments to be able to take a look!
