### ISSUE TITLE
Can't comment on article

### ISSUE THREAD

**Issue by kleenkanteen** [thedataquarry/old-zola-site#21]
Tried commenting but after logging in with github and pressing submit my comment never shows: https://thedataquarry.com/posts/vector-db-1/

Comments are served by https://giscus.app using github issues. API calls to giscus.app are failing as shown in chrome devtools. I think when you migrated your blog to `thedataquarry` organization, you forgot to update what repo giscus points to so it tries opening an issue in the old archived blog repo.

**Comment by prrao87** [comment]
Ah, I might have forgotten to regenerate the data IDs on giscus when I did the migration. I just did so now in df34a98.

Could you give this a try with the original comment you posted? Thanks a lot for the feedback btw!

**Comment by kleenkanteen** [comment]
Working good now 👍
